from autogen_core.tools import FunctionTool
from utilities.opentargets_tool import (
    search_disease_by_name,
    extract_top_targets_summary,
)


from utilities.pubmed_tool import search_and_fetch_articles
from utilities.save_pdf import save_pdf

from utilities.chembl import (
    search_compounds, get_compound_info, get_compound_structure,
    search_activities, get_assay_info, batch_compound_lookup
)

# ChEMBL compound search tool


compound_search = FunctionTool(
    search_compounds,
    description=(
        "Search for compounds in the ChEMBL database based on a query string. "
        "Input: (query: str, max_results: int) "
        "Output: list of compounds. "
        "Query is the search query (e.g., 'aspirin'), "
        "max_results is the maximum number of compounds to retrieve."
    ),
)
# ChEMBL compound information retrieval tool
compound_info = FunctionTool(
    get_compound_info,
    description=(
        "Retrieve detailed information about a compound from the ChEMBL database using its ChEMBL ID. "
        "Input: (chembl_id: str) "
        "Output: dict containing compound information. "
        "chembl_id is the ChEMBL identifier of the compound (e.g., 'CHEMBL25')."
    ),
)
# ChEMBL compound structure retrieval tool
compound_structure = FunctionTool(
    get_compound_structure,
    description=(   
        "Retrieve the molecular structure of a compound from the ChEMBL database using its ChEMBL ID. "
        "Input: (chembl_id: str) "
        "Output: str representing the molecular structure in SMILES format. "
        "chembl_id is the ChEMBL identifier of the compound (e.g., 'CHEMBL25')."
    ),
)
# ChEMBL activity search tool
activity_search = FunctionTool(
    search_activities,
    description=(
        "Search for biological activities of compounds in the ChEMBL database based on a target or assay. "
        "Input: (target_id: str, max_results: int) "
        "Output: list of activities. "
        "target_id is the identifier of the target or assay (e.g., 'CHEMBL210'). "
        "max_results is the maximum number of activities to retrieve."
    ),
)
# ChEMBL assay information retrieval tool
assay_info = FunctionTool(
    get_assay_info,
    description=(
        "Retrieve detailed information about an assay from the ChEMBL database using its assay ID. "
        "Input: (assay_id: str) "
        "Output: dict containing assay information. "
        "assay_id is the ChEMBL identifier of the assay (e.g., 'CHEMBL210')."
    ),
)
# ChEMBL batch compound lookup tool
batch_compound_lookup_tool = FunctionTool(
    batch_compound_lookup,
    description=(
        "Perform a batch lookup of multiple compounds in the ChEMBL database using a list of ChEMBL IDs. "
        "Input: (chembl_ids: list) "
        "Output: list of dicts containing compound information for each ChEMBL ID. "
        "chembl_ids is a list of ChEMBL identifiers (e.g., ['CHEMBL25', 'CHEMBL210'])."
    ),
)       

# PubMed search and fetch tool
search_for_articles = FunctionTool(
    search_and_fetch_articles,
    description=(
        "Search and fetch relevant articles from PubMed, given a search keyword. "
        "Input: (query: str, max_results: int) "
        "Output: list of articles. "
        "Query is the search query example 'breast cancer targets' or 'diabetes', "
        "max_results is the maximum number of articles to retrieve."
    ),
)

# Open Targets disease-target analysis tool
search_for_disease = FunctionTool(
    search_disease_by_name,
    description=(
        "Search for diseases by name using the Open Targets Platform API and return the top results ranked by score. "
        "Input: (disease_name: str, size: int) "
        "Output: List of dicts with 'id', 'name', 'entity', and 'score'."
    ),
)

extract_targets_summary = FunctionTool(
    extract_top_targets_summary,
    description=(
        "Extract and summarize the top target genes associated with a disease from Open Targets data."
        "Input: (efo_id: int, size: int) "
        "Output: A concise summary of the top target genes and their relevance to the disease. "
        "targets_data: returned targets from get_targets tool (list of dicts)."
        "default size is 4."
    ),
)



# Save PDF tool
save_to_pdf = FunctionTool(
    save_pdf,
    description=(
        "Save the content as a professionally formatted PDF file. "
        "Input: (content_markdown: str, filename: str, title: str) "
        "Output: The path to the saved PDF file. "
        "content_markdown: The content generated by the report agent in markdown format. "
        "filename: The desired filename for the PDF (e.g., 'report.pdf'). "
        "title: The title to display on the PDF cover page."
    ),
)
